### ISSUE TITLE
Failed to upload files from qeta page to s3 

### ISSUE THREAD

**Issue by yoramshai** [drodil/backstage-plugin-qeta#248]
I have the following settings in my app-config.yaml:

```
qeta:
  allowAnonymous: true
  allowMetadataInput: false
  entities:
    kinds: ['Component']
    max: 3
  tags:
    allowCreation: true
    allowedTags:
      - aws
      - github
      - ci/cd
    max: 5
  storage:
    disabled: false
    type: s3
    maxSizeImage: 2500000
    folder: /tmp/backstage-qeta-images
    # allowedMimeTypes:
    #   - png
    #   - jpg
    #   - jpeg
    #   - gif
    bucket: ${BUCKET}
    accessKeyId: ${S3_ACCESS_KEY_ID}
    secretAccessKey: ${S3_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
    # sessionToken: ${AWS_SESSION_TOKEN}

```

When I'm adding the attachment, I'm getting the below error: 
`qeta error Request failed with status 500 attachment.created.toUTCString is not a function type=errorHandler stack=TypeError: attachment.created.toUTCString is not a function` 

Did I miss something, or is this a bug ?
